### PR TITLE
Added example of automatic tests

### PR DESCRIPTION
**Pull request by boris-il-forte**
- Added new_test target to generate test executable
- Updated CMakeLists.txt to add test as subfolder
- Added two test using executable new_test
- Now you can run test suite by just typing either "make test" or "ctest" in the build directory

### CODE REVIEW

**Comment by boris-il-forte** [comment]
This is only an example of adding automated test for nlopt, using cmake. The main issue is that now nlopt doesn't build automatically using cmake, autotools are needed. It would be nice to make first a pure cmake build: this can be possible simply adding the code generation in the CMakeLists.txt.

If you can point out the commands to trigger autogeneration or, even better, the makefiles used in the process, I can enable full build from cmake withouth the need of autogenerated files in the repository.

Also I can implement new tests or adapt the existing ones to the ctest framework to have a clean and automated test suite.

**Comment by stevengj** [comment]
@boris-il-forte, the automake build is the primary one for development.  I would prefer that the tests be added there.

The `cmake` build is mainly only for Windows users.

**Comment by stevengj** [comment]
Do these tests actually pass, due to #40?

**Comment by stevengj** [comment]
There is also a built-in `testopt` program; the simplest thing would be to have a shell script that runs it automatically with various options.

**Comment by boris-il-forte** [comment]
Personally, I use only linux and I only use cmake, whenever possible, as is easier and cleaner wrt autotools.
I don't know any automatic test suite framework that can be used with autotools, but they exist for sure.
However I'm not able to use autotools properly, so I cannot help with that.
Due to #40, actually one test pass (MMA) and one test fails (LBFGS). However pass/fail is not so well defined for my sample test: simply a pass occurs where there are no exceptions (and main return 0).

Of course you can define a well defined problem with a known optimum and check if the optimization algorithm works correctly by measuring some distance from the solution and returning 0 (pass) or -1 (fail) when the condition is not met. Or you can use assertion or exception as well.

**Comment by stevengj** [comment]
@boris-il-forte, automake has built-in support for test programs (see the manual).  But you can also simply just write a test script that is executed by `make check`.

**Comment by jschueller** [comment]
:+1:  for this, would you consider dropping autotools ?

**Comment by boris-il-forte** [comment]
I was looking for Autotools test suite, and I see that is unnecessarily complex and unclean. So I'm not going to implement that in an autotools-like fashion. I can consider to write a shell script when I'll have time...

(Personally I think autotools are extremely unclean and unnecessarily complex...)

**Comment by stevengj** [comment]
There's a fair amount of functionality in the `configure.ac` file; it would be hard to convince me that you've replicated all of this in `cmake`.

**Comment by jschueller** [comment]
I see it's missing guile/octave/matlab bindings, and pkgconfig generation, got something else in mind ?

**Comment by stevengj** [comment]
https://github.com/stevengj/nlopt/blob/master/m4/ax_c_threadlocal.m4, to pick the first example that pops out on a random scan.

**Comment by stevengj** [comment]
I guess it's not completely crazy.  Autotools deals with a lot more ancient Unix variations than cmake, but these days that is no longer so relevant.

**Comment by jschueller** [comment]
@stevengj, see https://github.com/jschueller/nlopt/commit/2d1122bfb752c61d198688200907802f810421bc

**Comment by jschueller** [comment]
all these are implemented in #49

**Pull request closed without merging**
