### PR TITLE
Remove use of long double in slsqp.c

### PR DESCRIPTION
**Pull request by AaronWebster**
Improves compatibility with ARM.  See [https://github.com/stevengj/nlopt/issues/413](https://github.com/stevengj/nlopt/issues/413)

### CODE REVIEW

**Review by jschueller — APPROVED** [review]

**Comment by stevengj** [comment]
On ARM, isn't `long double` simply a synonym for `double`?  I'm not opposed to this change, but I'm confused about why it would improve matters on ARM.

**Comment by ooosssososos** [comment]
Long doubles are just doubles in arm. But on x86 they are sometimes 80 bit. The discrepancy in numerical precision can be a problem when expecting the same output on x86 and ARM, especially since the small error caused by fp differences initially seems to increase over time and can result in sizeable differences in output across platforms. This can cause tests that expect some output to fail

**Comment by AaronWebster** [comment]
From what I understand as it's confined to the FPU on x86 systems long doubles are 80 bit and on arm they are 64 bit; he downcast to double can result in discrepancies which causes solution to diverge.  

https://developer.arm.com/documentation/dui0491/i/C-and-C---Implementation-Details/Basic-data-types

**Comment by stevengj** [comment]
> the downcast to double can result in discrepancies which causes solution to diverge.

Even if we use `double` on all platforms, we cannot guarantee exactly the same results on all platforms — e.g. differences in compiler optimizations (such as whether fused multiply adds are used) may change roundoff errors when you go from one system to the next.

**Pull request merged**
