### PR TITLE
Use octave_map

### PR DESCRIPTION
**Pull request by opoplawski**
This supports octave 4.0 and works at least in octave 3.8 if not earlier.

### CODE REVIEW

**Comment by stevengj** [comment]
We should be able to continue to support earlier versions if you add:
```
#include <octave/version.h>
#if OCTAVE_MAJOR_VERSION < 3 || (OCTAVE_MAJOR_VERSION == 3 && OCTAVE_MINOR_VERSION < 8)
#  define octave_map Octave_map
#endif
```

**Comment by opoplawski** [comment]
Actually, octave_map is present in octave 3.2, which is what is in EPEL5. So I don't think there is any need.

**Comment by stevengj** [comment]
I'd prefer to just keep backward compatibility since there is almost no cost to doing so (just four lines).

**Comment by opoplawski** [comment]
I'll let you do that then.  But the original change should be compatible with octave 3.2 without the conditional (as it has octave_map) which is 6 years old.

**Comment by acapobianchi** [comment]
@stevengj
Hello, first of all thank you for NLopt!

I'm trying to compile Octave 4.0 plugin with the *mkoctfile* command, as explained at http://ab-initio.mit.edu/wiki/index.php/NLopt_on_Windows

I've generated the library *libnlopt-0.lib* and, in file *nlopt_optimize-oct.cc*, I've replaced all *Octave_map* with *octave_map*.

Unfortunately the command:

*mkoctfile -lD:\Installers\NLopt\nlopt-2.4.2-dll64\libnlopt-0.lib --output nlopt_optimize.oct D:\Installers\NLopt\nlopt-2.4.2-dll64\nlopt_optimize-oct.cc*

fails, returning:

c:/octave/octave-4.0.0/bin/../lib/gcc/i686-w64-mingw32/4.9.2/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lD:\Installers\NLopt\nlopt-2.4.2-dll64\libnlopt-0.lib
collect2.exe: error: ld returned 1 exit status
warning: mkoctfile exited with failure status
warning: called from
    mkoctfile at line 171 column 5

I've checked that the .lib file exist in the specified folder.

Are there more detailed instructions for Octave plugin compilation?

Thank you very much!

**Pull request merged**
