### PR TITLE
Fix all uninitialized variable warnings

### LINKED ISSUE #133: Bobyqa uninitialised variables in rare cases
Hello,

I know this is a follow-up to issue #36 but I do not know how to re-open it. I stumbled on the same problem (segmentation fault in altmov_ due to two variables being uninitialised) when using bobyqa together with the augmented lagrangian and a small tolerance as stopping criterion (10^-12). 

I ended up modifying the code of bobyqa a very little which made it work:

 - line 764 : int ksav = 1;
- line 768 : int ibdsav = 1;

This is only an ugly correction but I would be curious to know if someone has a better option to avoid this (I suspect all of this comes from the optimised parameters being a tiny little outside the bounds when entering bobyqa - from auglag - , which does not check for it)

Thanks

### PR DESCRIPTION
**Pull request by jschueller**
Every variables that yields a -Wmaybe-uninitialized gcc warning are set to 0

Fixes #133

### CODE REVIEW

**Comment by ocommowi** [comment]
I tested (cf #36 comments) on my crashes and it does solve the problem on the few examples I have. Thanks again !

Looking at the code again I still have the feeling that variables used as indexes should be initialised to 1 rather than 0 for fortran codes converted to C (see in bobyqa.c, altmov_ function for example, all table pointers have a -- applied to them at the start of the function and thus index 0 should not be accessed). That's my humble opinion though, again I get lost easily with these indexing conventions problems

**Comment by jschueller** [comment]
I dont know. I tried looking at the original code, zero are also used. What happens if you initialize it to 8000 for example ?

**Comment by ocommowi** [comment]
Yes I agree too that the original code has an error. For me, the >0 and <0 branches of the code are there to handle possible negative indexes and make them positive again when searching in the tables, but 0 is not handled. That's also why I preferred to initialise at 1 but 0 is working for me, and as you said it will at least make it deterministic so it is good to do this initialization anyway.

**Comment by jschueller** [comment]
that's really unclear, I propose we stick to 0 everywhere.

**Comment by stevengj** [comment]
On the one hand, 0 is probably a good default when in doubt; this code was translated from Fortran (via f2c), and if I remember correctly there were ancient versions of Fortran in which variables were implicitly initialized to zero.  (The original author of this code, Powell, definitely harkens back to those days… it's very much Fortran-66 style spaghetti.)

On the other hand, you have to be careful about masking one bug with another bug by initializing to an arbitrary value... at least tools like valgrind can catch uses of uninitialized variables, but they can't catch incorrect initializations.

**Comment by stevengj** [comment]
Looking at the code, it seems right to be to use `ibdsav = 0`, causing it to skip the final `xnew[±ibdsav] = ...` assignment.   The preceding loop is supposed to identify the dimension where `predsq` is biggest, and uses `ibdsav` to push `xnew` in that dimension to the boundaries of the trust region.  But if for some strange reason `predsq` is not biggest along any direction (maybe because it is always zero??? not sure why this would happen), then it seems right not to do any further modification of `xnew`.

**Comment by jschueller** [comment]
ok thank you for peaking in

**Pull request merged**
