### PR TITLE
Back away from inequality constraints that evaluate to NaN

### PR DESCRIPTION
**Pull request by jpritikin**
This permits slsqp to deal with the interaction between inequality constraints and soft feasibility constraints.

### CODE REVIEW

**Comment by jpritikin** [comment]
Oops, this change is not passing all of my tests yet.

**Comment by jpritikin** [comment]
Actually these changes are good. The problem I was having was caused by use of ftol instead of xtol on a constrained problem.

**Comment by jpritikin** [comment]
How does this look?

**Comment by jpritikin** [comment]
Hm, do I need to save/restore slsqpb_state if I pick a point from the line search that is not the last point?

**Comment by stevengj** [comment]
@jpritikin, regarding the SAVE/RESTORE_STATE: if I remember correctly, the original Fortran code was using the equivalent of `static` C local variables for these things, and I wanted it to be re-entrant & thread-safe.   So, the state only needs saving inside the `slsqpb_`, and should be saved at every exit point from that function (unless you will never come back, e.g. you are exiting because you have converged or there was an error).

**Comment by stevengj** [comment]
Could you squash these (via `git rebase --interactive` followed by a `git push -f`) into a single commit?  Also be sure to put `(for #30)` in the commit message so that #30 will be cross-referenced.

**Comment by jpritikin** [comment]
> regarding the SAVE/RESTORE_STATE

This question was addressed with https://github.com/jpritikin/nlopt/commit/356bd27e08bbd20abb07534b6678257492ec8421

**Comment by stevengj** [comment]
Should the `s[i__] = x[i__] - x0[i__];` loop be executed every time we `goto L260`, or only from the beginning of the `slsqpb_` function?  Maybe you should move it before the relevant `goto`.

**Comment by jpritikin** [comment]
> Should the s[i__] = x[i__] - x0[i__]; loop be executed every time we goto L260, or only from the beginning of the slsqpb_ function? 

Sorry, I can't remember. Certainly the code doesn't hurt. It helps preserve an invariant condition that should be preserved.

**Comment by jschueller** [comment]
hello @jpritikin, do you think this has a chance to land someday or do you think we can close it ?

**Comment by jpritikin** [comment]
I personally have given up. The changes are part of OpenMx. I believe the version of the code in OpenMx is superior to what I started with when I copied it from here, but I haven't kept track of nlopt and I have also ceased to contribute to OpenMx.

**Comment by jschueller** [comment]
thanks

**Pull request closed without merging**
