### PR TITLE
improve the MATLAB bindings

### PR DESCRIPTION
**Pull request by amroamroamro**
Several improvements to the mex-file.
Commit messages give a summary of the changes.

### CODE REVIEW

**Comment by jschueller** [comment]
seems a nice set of change, could you rebase to current master ?
we switched to cmake and you may have to modify octave/CMakeLists.txt

**Comment by amroamroamro** [comment]
@jschueller 
I see.. I will close this one and create another PR on top of the new master.

This also invalidates another branch of mine where I've been working on getting nlopt compiled on Windows/AppVeyor using mingw-64 and the existing autotools build system: https://github.com/amroamroamro/nlopt/blob/appveyor/appveyor.yml

**Comment by jschueller** [comment]
@amroamroamro we use appveyor to test the build on msvc, and travis to build with mingw.

**Comment by amroamroamro** [comment]
yes, I saw the new changes. The nice thing about appveyor is that you can save the build artifacts, so you can use it to build the precompiled windows binaries distributed on the main site.

**Comment by jschueller** [comment]
With travis too if you're curious, with the deploy keyword.

**Comment by amroamroamro** [comment]
oh I just noticed, you're cross-compiling Windows binaries from Linux/Travis. Nice!

**Comment by jschueller** [comment]
@amroamroamro any change you give this another try ?

**Comment by amroamroamro** [comment]
@jschueller sorry for taking too long, I'll revisit this and submit a new pull request asap.

**Comment by amroamroamro** [comment]
@jschueller see my new PR at #83.
This also includes several update to the cmake scripts, can you please review?

**Pull request closed without merging**
