### PR TITLE
Do not install guile 2.2 until supported in swig

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by stevengj** [comment]
Is this due to swig/swig#312?  Or is there some other issue beyond just deprecation warnings?

**Comment by jschueller** [comment]
No, it's deeper than that: https://github.com/swig/swig/commit/24fba025710b08d2d1da7cc734ca164aa6e1acbc

**Comment by stevengj** [comment]
What was the error message?

**Comment by jschueller** [comment]
Some API changes:
```
Scanning dependencies of target nlopt_cxx_guile

[ 80%] Building CXX object swig/CMakeFiles/nlopt_cxx_guile.dir/nlopt-guile.cpp.o

/Users/travis/build/stevengj/nlopt/build/swig/nlopt-guile.cpp:1357:36: error: use of undeclared identifier 'scm_make_real'

    SCM_SIMPLE_VECTOR_SET(xscm, i, scm_make_real(x[i]));

                                   ^

/Users/travis/build/stevengj/nlopt/build/swig/nlopt-guile.cpp:1785:9: error: use of undeclared identifier 'scm_listify__GONE__REPLACE_WITH__scm_list_n'

        scm_listify(SWIG_NewPointerObj(temp, SWIGTYPE_p_std__out_of_range, 1),

        ^

/usr/local/include/guile/2.2/libguile/deprecated.h:115:21: note: expanded from macro 'scm_listify'

#define scm_listify scm_listify__GONE__REPLACE_WITH__scm_list_n

                    ^

/Users/travis/build/stevengj/nlopt/build/swig/nlopt-guile.cpp:1823:9: error: use of undeclared identifier 'scm_listify__GONE__REPLACE_WITH__scm_list_n'

        scm_listify(SWIG_NewPointerObj(temp, SWIGTYPE_p_std__out_of_range, 1),

        ^

/usr/local/include/guile/2.2/libguile/deprecated.h:115:21: note: expanded from macro 'scm_listify'

#define scm_listify scm_listify__GONE__REPLACE_WITH__scm_list_n

                    ^

/Users/travis/build/stevengj/nlopt/build/swig/nlopt-guile.cpp:1864:9: error: use of undeclared identifier 'scm_listify__GONE__REPLACE_WITH__scm_list_n'

        scm_listify(SWIG_NewPointerObj(temp, SWIGTYPE_p_std__out_of_range, 1),

        ^

/usr/local/include/guile/2.2/libguile/deprecated.h:115:21: note: expanded from macro 'scm_listify'

#define scm_listify scm_listify__GONE__REPLACE_WITH__scm_list_n

                    ^

4 errors generated.

make[2]: *** [swig/CMakeFiles/nlopt_cxx_guile.dir/nlopt-guile.cpp.o] Error 1

make[1]: *** [swig/CMakeFiles/nlopt_cxx_guile.dir/all] Error 2

make: *** [all] Error 2

'```

https://travis-ci.org/stevengj/nlopt/jobs/213207681

**Comment by stevengj** [comment]
The `scm_make_real` call is [our fault](https://github.com/stevengj/nlopt/blob/170f352492e555c6ebd706b376c90b4f927587f3/swig/nlopt-guile.i#L49).   `scm_listify` seems to be swig's fault.

**Pull request merged**
