### PR TITLE
[pkgconfig] Mark libm as private

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by stevengj** [comment]
What does this do?

**Comment by jschueller** [comment]
This means libm is internally linked to libnlopt but programs linked to libnlopt do not need to link to libm,
see https://gentoobrowse.randomdan.homeip.net/packages/sci-libs/nlopt

**Comment by stevengj** [comment]
Does that only work on systems whose runtime linkers automatically pull in shared-library dependencies?  Or is pkgconfig smart enough to merge `Libs.private` with `Libs` if the system does not support "private" libs?

I guess that is most systems these days, but ancient Unices didn't support this feature.  Maybe we don't care about those anymore.

**Comment by jschueller** [comment]
I may be too young to tell. But this seems pretty standard to wirte pkgconfig files this way.

**Pull request merged**
